repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.269"
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.3.0'
  hooks:
    - id: mypy
- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: v0.1
  hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
