repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.269"
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''
  hooks:
    - id: mypy
- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: cc59b0431a5d072786b59430e9b342b2881064f6
  hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
