GET {{host}}/endpoints
###
GET {{host}}/endpoints/f65d954963564a9c975c9bd52dc529e7
###
POST {{host}}/endpoints
###
DELETE {{host}}/endpoints/eff70afbed6c40358aaf53711a2a147e
###
GET {{host}}/endpoints/f65d954963564a9c975c9bd52dc529e7/traffic
###
