GET {{host}}/r/123abc?a=1&b=2&c=3
Set-Cookie: cookie1=1234
Content-Type: application/json

{
    "test": "test"
}

###
POST {{host}}/r/123abc
###
PUT {{host}}/r/123abc
###
PATCH {{host}}/r/123abc
###
DELETE {{host}}/r/123abc
###
OPTIONS {{host}}/r/123abc
###
HEAD {{host}}/r/123abc
###
TRACE {{host}}/r/123abc
###
