"""baseline

Revision ID: 0.0.1
Revises: 
Create Date: 2025-01-26 14:03:10.613368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0.0.1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_request',
    sa.Column('endpoint_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('request_line', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_request_header',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_request_id'], ['inbound_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_request_query_params',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_request_id'], ['inbound_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_response')
    op.drop_table('match')
    op.drop_table('inbound_request_query_params')
    op.drop_table('inbound_request_header')
    op.drop_table('user')
    op.drop_table('rule')
    op.drop_table('inbound_request')
    # ### end Alembic commands ###
