"""Baseline schema

Revision ID: 0.0.1
Revises: 
Create Date: 2023-06-25 16:43:59.175832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0.0.1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_code', sa.String(length=255), nullable=False),
    sa.Column('verb', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.String(length=255), nullable=False),
    sa.Column('query_params', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('inbound_requests')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
